# Generated by Django 3.2.7 on 2023-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electricity_monthly', models.IntegerField()),
                ('Yearly_distance_travelled_petrol', models.IntegerField()),
                ('Yearly_distance_travelled_diesel', models.IntegerField()),
                ('LPG_qty', models.IntegerField()),
            ],
        ),
    ]
